branch-defaults:
  master:
    environment: bio-site
    group_suffix: null
global:
  application_name: bio_site
  default_ec2_keyname: sarah
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
